src/main/java/cz/vut/fit/gja/dto/ProjectDto.java
package cz.vut.fit.gja.dto;

import cz.vut.fit.gja.Scopes;
import cz.vut.fit.gja.constants.FacesConstants;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import javax.validation.constraints.Size;
import java.io.Serializable;
import java.text.SimpleDateFormat;
import java.util.Collections;
import java.util.Date;
import java.util.List;
import java.util.logging.Logger;

/**
 *
 */
@Scope(Scopes.SESSION)
@Component
public class ProjectDto implements Serializable {
    
    public static final String BEAN_NAME = "projectDto";
    
    private Integer id;
    private String code = "";
    private String language;
    private LanguageDto languageDto;
    private String title = "";
    private Date expiration;
    @Size(max = FacesConstants.DESCRIPTION_LENGTH)
    private String description;
    private List<TagDto> selectedTags = Collections.emptyList();
    private Date created;
    private int downloadCount;
    private short rating;
    private int votes;
    private List<TagDto> tagList = Collections.emptyList();
    
    public Integer getId() {
        Logger logger = Logger.getLogger("projectDto");
        logger.info("getId() = " + id);
        return id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    
    public String getCode() {
        return code;
    }
    
    public void setCode(String code) {
        this.code = code;
    }
    
    public String getLanguage() {
        return language;
    }
    
    public void setLanguage(String language) {
        this.language = language;
    }
    
    public String getTitle() {
        return title;
    }
    
    public String getTitleHighligted(String query) {
        return title.replaceAll(query, "<span style='background-color: #ffff00;'>" + query + "</span>");
    }
    
    public void setTitle(String title) {
        this.title = title;
    }
    
    public String getStringExpiration() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return (expiration != null ? dateFormat.format(expiration) : "<em>unknown</em>");
    }
    
    public String getStringCreated() {
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        return (created != null ? dateFormat.format(created) : "<em>unknown</em>");
    }
    
    public Date getExpiration() {
        return expiration;
    }
    
    public void setExpiration(Date expiration) {
        this.expiration = expiration;
    }
    
    public boolean isValidFileUpload() {
        return language != null && title != null;
    }
    
    public void setDescription(String description) {
        this.description = description;
    }
    
    public String getDescription() {
        return description;
    }
    
    public String getDescriptionHighlighted(String query) {
        return getDescription().replaceAll(query, "<span style='background-color: #ffff00;'>" + query + "</span>");
    }
    
    public void setSelectedTags(List<TagDto> selectedTags) {
        if (selectedTags != null) {
            this.selectedTags = selectedTags;
        } else {
            this.selectedTags = Collections.emptyList();
        }
    }
    
    public List<TagDto> getSelectedTags() {
        return selectedTags;
    }
    
    public String getTags() {
        List<TagDto> list = getTagList();
        if (list.isEmpty()) {
            return "<em>no tags specified</em>";
        }
        
        String ret = list.get(0).getName();
        if (list.size() > 1) {
            for (int i = 1; i < list.size(); i++) {
                TagDto tagDto = list.get(i);
                ret += ", " + tagDto.getName();
            }
        }
        return ret;
    }
    
    public void setCreated(Date created) {
        this.created = created;
    }
    
    public Date getCreated() {
        return created;
    }
    
    public void setDownloadCount(int downloadCount) {
        this.downloadCount = downloadCount;
    }
    
    public int getDownloadCount() {
        return downloadCount;
    }
    
    public void setRating(short rating) {
        this.rating = rating;
    }
    
    public short getRating() {
        return rating;
    }
    
    public int getVotes() {
        return votes;
    }
    
    public void setVotes(int votes) {
        this.votes = votes;
    }
    
    public void setTagList(List<TagDto> tagList) {
        this.tagList = tagList;
    }
    
    public List<TagDto> getTagList() {
        return tagList;
    }
    
    public LanguageDto getLanguageDto() {
        return languageDto;
    }
    
    public void setLanguageDto(LanguageDto languageDto) {
        this.languageDto = languageDto;
    }
}

src/main/java/cz/vut/fit/gja/controllers/ProjectController.java
package cz.vut.fit.gja.controllers;

import cz.vut.fit.gja.Scopes;
import cz.vut.fit.gja.constants.FacesConstants;
import cz.vut.fit.gja.controllers.data.LazyProjectModel;
import cz.vut.fit.gja.controllers.data.ProjectDataFilter;
import cz.vut.fit.gja.controllers.util.TagsAutocompleteBean;
import cz.vut.fit.gja.dto.ProjectDto;
import cz.vut.fit.gja.entities.Language;
import cz.vut.fit.gja.entities.Project;
import cz.vut.fit.gja.services.LanguageService;
import cz.vut.fit.gja.services.ProjectService;
import org.apache.log4j.Logger;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.RateEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static cz.vut.fit.gja.constants.FacesConstants.PROJECT_DETAIL;
import static cz.vut.fit.gja.constants.FacesConstants.REDIRECT;
import cz.vut.fit.gja.utils.FileSystemUtils;
import cz.vut.fit.gja.utils.SourceCodeFile;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.file.Files;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

@Lazy
@Scope(Scopes.VIEW)
@Controller
public class ProjectController extends BaseController implements Serializable {

    private static final Logger logger = Logger.getLogger(ProjectController.class);

    @Autowired
    private ProjectService projectService;

    @Autowired
    private LanguageService languageService;

    @Autowired
    private TagsAutocompleteBean autocompleteBean;

    private ProjectDto projectDto;

    private SourceCodeFile selectedSCFile;

    public ProjectController() {
    }

    public void create(ProjectDto projectDto) {
        projectService.create(projectDto);
    }

    public ProjectDto find(String idStr) {
        try {
            int id = Integer.valueOf(idStr);
            ProjectDto projectDto = find(id);
            this.projectDto = projectDto;
            return projectDto;
        } catch (NumberFormatException e) {
            return null;
        }

    }

    public ProjectDto find(int id) {
        if (id == 0) {
            return null;
        }
        ProjectDto projectDto = projectService.find(id);
        return projectDto;
    }

    public void loadProjectBean(int id) {

        ProjectDto dto = find(id);
        if (dto != null) {
            projectDto = dto;
        }
    }

    public void load(ComponentSystemEvent event) {
        String projectId = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap().get(FacesConstants.PARAM_PROJECT_ID);
        int id;
        try {
            id = Integer.valueOf(projectId);
        } catch (NumberFormatException e) {
            id = 0;
        }

        loadProjectBean(id);
    }

    public List<ProjectDto> findAll() {
        return projectService.findAll();
    }

    public List<ProjectDto> findAllByFilter() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        if (filter != null && filter.getLanguageName() != null) {
            return projectService.findByLanguage(filter.getLanguageName());
        }

        if (filter != null && filter.getTagName() != null) {
            return projectService.findByTag(filter.getTagName());
        }

        return Collections.emptyList();
    }

    public boolean isFiltered() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        return filter != null && (filter.getLanguageName() != null || filter.getTagName() != null);
    }

    public LazyProjectModel getLazyModel() {
        return new LazyProjectModel(projectService.findAll());
    }

    public String onFlowProcess(FlowEvent event) {
        return event.getNewStep();
    }

    protected void linkWithTags(ProjectDto projectDto) {
        projectService.linkWithTags(projectDto);
    }

    public boolean isOneFile() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length == 1);
    }

    public boolean isMoreFiles() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length > 1);
    }

    public String getFilesSourceCode(File name) {
        String code = "";
        try {
            CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
            decoder.onMalformedInput(CodingErrorAction.IGNORE);
            InputStreamReader sreader = new InputStreamReader(new FileInputStream(name), decoder);
            BufferedReader reader = new BufferedReader(sreader);
            String line;
            while ((line = reader.readLine()) != null) {
                code += line + "\n";
            }
        } catch (IOException ex) {
            return "An error while opening file occured! We are sorry.";
        }

        return code;
    }

    public String getSourceCodeFromFile(File file) {
        if (file.isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(file), decoder);
                BufferedReader reader = new BufferedReader(sreader);
                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                return "An error while opening file occured! We are sorry.";
            }

            return code;
        }
        return "An error occured, file " + file.getName() + " is not file!";
    }

    public String getSourceCode() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();

        if (list[0].isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(list[0]), decoder);
                BufferedReader reader = new BufferedReader(sreader);

                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                return "An error while opening file occured! We are sorry. " + ex.getMessage();
            }

            return code;
        }
        return "An error occured, file " + list[0].getName() + " is not file!";
    }

    public TreeNode getRoot() {
        TreeNode root = new DefaultTreeNode("root", null);
        root.setExpanded(true);
        root.setSelectable(false);

        if (projectDto != null) {
            File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
            getFolderContent(projectDataStore, root);
        }
        return root;
    }

    private void getFolderContent(File folder, TreeNode parentNode) {
        File[] list = folder.listFiles();

        for (File file : list) {
            if (file.isFile()) {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), FilenameUtils.getExtension(file.getName()), file.length(), file), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
            } else {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), "Folder", 0), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
                getFolderContent(file, node);
            }
        }
    }

    public SourceCodeFile getSelectedSCFile() {
        logger.debug("getSelectedSCFile");
        return selectedSCFile;
    }

    public void setSelectedSCFile(SourceCodeFile selectedSCFile) {
        logger.debug("setSelectedSCFile");
        this.selectedSCFile = selectedSCFile;
    }

    public List<String> getLanguages() {
        return languageNames(languageService.findAll());
    }

    public List<SelectItem> getLanguagesSelectItems() {
        return getLanguageItems(languageService.findAll());
    }

    private List<SelectItem> getLanguageItems(List<Language> all) {
        ArrayList<SelectItem> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(new SelectItem(language.getId(), language.getName()));
        }
        return langs;
    }

    private List<String> languageNames(List<Language> all) {
        ArrayList<String> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(language.getName());
        }

src/main/webapp/pages/project/Create.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProjectCreateDlg" widgetVar="ProjectCreateDialog" modal="true" resizable="false" appendTo="@(body)" header="#{localization.CreateProjectTitle}">
            <h:form id="ProjectCreateForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{projectController.selected != null}">
                        <p:outputLabel value="#{localization.CreateProjectLabel_id}" for="id" />
                        <p:inputText id="id" value="#{projectController.selected.id}" title="#{localization.CreateProjectTitle_id}" required="true" requiredMessage="#{localization.CreateProjectRequiredMessage_id}"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_description}" for="description" />
                        <p:inputTextarea rows="4" cols="30" id="description" value="#{projectController.selected.description}" title="#{localization.CreateProjectTitle_description}" />
                        <p:outputLabel value="#{localization.CreateProjectLabel_path}" for="path" />
                        <p:inputTextarea rows="4" cols="30" id="path" value="#{projectController.selected.path}" title="#{localization.CreateProjectTitle_path}" required="true" requiredMessage="#{localization.CreateProjectRequiredMessage_path}"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_created}" for="created" />
                        <p:calendar id="created" pattern="MM/dd/yyyy HH:mm:ss" value="#{projectController.selected.created}" title="#{localization.EditProjectTitle_created}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_created}" showOn="button"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_exprired}" for="exprired" />
                        <p:calendar id="exprired" pattern="MM/dd/yyyy HH:mm:ss" value="#{projectController.selected.exprired}" title="#{localization.EditProjectTitle_exprired}"  showOn="button"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_rating}" for="rating" />
                        <p:inputText id="rating" value="#{projectController.selected.rating}" title="#{localization.CreateProjectTitle_rating}" />
                        <p:outputLabel value="#{localization.CreateProjectLabel_votes}" for="votes" />
                        <p:inputText id="votes" value="#{projectController.selected.votes}" title="#{localization.CreateProjectTitle_votes}" required="true" requiredMessage="#{localization.CreateProjectRequiredMessage_votes}"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_downloadCount}" for="downloadCount" />
                        <p:inputText id="downloadCount" value="#{projectController.selected.downloadCount}" title="#{localization.CreateProjectTitle_downloadCount}" required="true" requiredMessage="#{localization.CreateProjectRequiredMessage_downloadCount}"/>
                        <p:outputLabel value="#{localization.CreateProjectLabel_languageId}" for="languageId" />
                        <p:selectOneMenu id="languageId" value="#{projectController.selected.language}" >
                            <f:selectItems value="#{languageController.itemsAvailableSelectOne}"
                                           var="languageIdItem"
                                           itemValue="#{languageIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{projectController.create}" value="#{localization.Save}" update="display,:ProjectListForm:datalist,:growl" oncomplete="handleSubmit(args,'ProjectCreateDialog');"/>
                    <p:commandButton value="#{localization.Cancel}" onclick="ProjectCreateDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>

src/main/webapp/pages/project/Detail.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui"
      xmlns:c="http://java.sun.com/jsp/jstl/core">

    <ui:composition template="../../resources/template/main.xhtml">

        <ui:define name="header">
            Code Portal - Project Detail
        </ui:define>


        <ui:param name="pageTitle" value="Project detail | Code Portal" />

        <ui:define name="main">
            <f:metadata>
                <f:event type="preRenderView" listener="#{projectController.load}"/>
            </f:metadata>
            <c:set var="projectDto" value="#{projectController.projectDto}"/>
            <!--@elvariable id="projectDto" type="cz.vut.fit.gja.dto.ProjectDto"-->

            <h:panelGroup rendered="#{projectDto == null}">
                <br/>
                <h3>An error occured</h3>
                <p>This project does not exist :-(</p>
            </h:panelGroup>

            <h:form id="form" rendered="#{projectDto != null}">
                <!-- DESCRIPTION -->
                <div class="well">
                    <h2>#{projectDto.title}</h2>
                    <h:outputText value="#{projectDto.description}" escape="false" />
                </div>

                <!-- SOURCE CODE -->
                <div class="well">
                    <h2>Source code</h2>

                    <!-- JUST ONE FILE -->
                    <h:panelGroup rendered="#{projectController.oneFile}">
                        <script type="text/javascript" src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
                        <pre class="prettyprint linenums lang-scm">#{projectController.getSourceCode()}</pre>
                    </h:panelGroup>

                    <!-- MORE FILES -->
                    <p:treeTable rendered="#{projectController.moreFiles}" id="treetable" value="#{projectController.root}" var="scfile"> 

                        <p:column style="width:60%">  
                            <f:facet name="header">  
                                File name
                            </f:facet>  
                            <h:outputText value="#{scfile.name}" />  
                        </p:column>  

                        <p:column style="width:10%">  
                            <f:facet name="header">  
                                Size  
                            </f:facet>  
                            <h:outputText value="#{scfile.sizeInKb} kB" />  
                        </p:column>  

                        <p:column style="width:26%">  
                            <f:facet name="header">  
                                Type  
                            </f:facet>  
                            <h:outputText value="#{scfile.type}" />  
                        </p:column>

                        <p:column style="width:4%">  
                            <p:commandLink update=":form:documentPanel" oncomplete="PF('documentDialog').show()" title="View Detail" styleClass="ui-icon ui-icon-search" rendered="#{scfile.type != 'Folder'}">  
                                <f:setPropertyActionListener value="#{scfile}" target="#{projectController.selectedSCFile}" />  
                            </p:commandLink>  
                        </p:column> 
                    </p:treeTable>

                    <!-- DIALOG -->
                    <p:dialog id="dialog" header="File Detail" showEffect="fade" widgetVar="documentDialog" modal="true">  
                        <p:scrollPanel id="documentPanel" mode="native" style="width:700px;height:400px">
                            <h:panelGroup rendered="#{not empty projectController.selectedSCFile}">
                                <script type="text/javascript" src="https://google-code-prettify.googlecode.com/svn/loader/run_prettify.js"></script>
                                <pre class="prettyprint linenums lang-scm">#{projectController.getSourceCodeFromFile(projectController.selectedSCFile.file)}</pre>
                            </h:panelGroup>

                        </p:scrollPanel>  
                    </p:dialog>
                </div>

                <!-- TABLE WITH INFORMATION -->
                <div class="well">
                    <p:growl id="messages" showDetail="true"/>

                    <h:panelGrid columns="2" cellpadding="5" border="1" id="table">

                        <h:outputText value="Language:" />
                        <h:outputText value="#{projectDto.languageDto.name}" escape="false" />

                        <h:outputText value="Tags:" />
                        <h:outputText value="#{projectDto.tags}" escape="false" />

                        <h:outputText value="Created:" />
                        <h:outputText value="#{projectDto.stringCreated}" escape="false" />

                        <h:outputText value="Expiration:" />
                        <h:outputText value="#{projectDto.stringExpiration}" escape="false" />

                        <h:outputText value="Downloaded:" />
                        <h:outputText value="#{projectDto.downloadCount}×" />

                        <h:outputLabel for="rating" value="Rating:"/>
                        <p:rating id="rating" value="#{projectController.rating}" cancel="false" readonly="true"/>

                        <h:outputText value="Votes:"/>
                        <h:outputText id="votes" value="#{projectController.votes}" />

                        <h:outputLabel for="rate" value="Your rating: "/>
                        <p:rating id="rate" cancel="false" widgetVar="rateWidget" onRate="rateWidget.disable()">
                            <p:ajax event="rate" listener="#{projectController.onRate}" update="messages votes rating"/>
                        </p:rating>

                    </h:panelGrid>

                    <br/>
                    <p:commandButton value="Download ZIP" ajax="false">
                        <p:fileDownload value="#{projectController.download}" />
                    </p:commandButton>
                </div>

            </h:form>
        </ui:define>

    </ui:composition>
</html>

src/main/webapp/pages/project/Edit.xhtml
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:ui="http://java.sun.com/jsf/facelets"
      xmlns:h="http://java.sun.com/jsf/html"
      xmlns:f="http://java.sun.com/jsf/core"
      xmlns:p="http://primefaces.org/ui">

    <ui:composition>

        <p:dialog id="ProjectEditDlg" widgetVar="ProjectEditDialog" modal="true" resizable="false" appendTo="@(body)" header="#{localization.EditProjectTitle}">
            <h:form id="ProjectEditForm">
                <h:panelGroup id="display">
                    <p:panelGrid columns="2" rendered="#{projectController.selected != null}">
                        <p:outputLabel value="#{localization.EditProjectLabel_id}" for="id" />
                        <p:inputText id="id" value="#{projectController.selected.id}" title="#{localization.EditProjectTitle_id}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_id}"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_description}" for="description" />
                        <p:inputTextarea rows="4" cols="30" id="description" value="#{projectController.selected.description}" title="#{localization.EditProjectTitle_description}" />
                        <p:outputLabel value="#{localization.EditProjectLabel_path}" for="path" />
                        <p:inputTextarea rows="4" cols="30" id="path" value="#{projectController.selected.path}" title="#{localization.EditProjectTitle_path}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_path}"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_created}" for="created" />
                        <p:calendar id="created" pattern="MM/dd/yyyy HH:mm:ss" value="#{projectController.selected.created}" title="#{localization.EditProjectTitle_created}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_created}" showOn="button"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_exprired}" for="exprired" />
                        <p:calendar id="exprired" pattern="MM/dd/yyyy HH:mm:ss" value="#{projectController.selected.exprired}" title="#{localization.EditProjectTitle_exprired}"  showOn="button"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_rating}" for="rating" />
                        <p:inputText id="rating" value="#{projectController.selected.rating}" title="#{localization.EditProjectTitle_rating}" />
                        <p:outputLabel value="#{localization.EditProjectLabel_votes}" for="votes" />
                        <p:inputText id="votes" value="#{projectController.selected.votes}" title="#{localization.EditProjectTitle_votes}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_votes}"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_downloadCount}" for="downloadCount" />
                        <p:inputText id="downloadCount" value="#{projectController.selected.downloadCount}" title="#{localization.EditProjectTitle_downloadCount}" required="true" requiredMessage="#{localization.EditProjectRequiredMessage_downloadCount}"/>
                        <p:outputLabel value="#{localization.EditProjectLabel_languageId}" for="languageId" />
                        <p:selectOneMenu id="languageId" value="#{projectController.selected.language}" >
                            <f:selectItem itemLabel="#{localization.SelectOneMessage}"/>
                            <f:selectItems value="#{languageController.itemsAvailableSelectOne}"
                                           var="languageIdItem"
                                           itemValue="#{languageIdItem}"/>
                        </p:selectOneMenu>
                    </p:panelGrid>
                    <p:commandButton actionListener="#{projectController.update}" value="#{localization.Save}" update="display,:ProjectListForm:datalist,:growl" oncomplete="handleSubmit(args, 'ProjectEditDialog');"/>
                    <p:commandButton value="#{localization.Cancel}" onclick="ProjectEditDialog.hide()"/>
                </h:panelGroup>
            </h:form>
        </p:dialog>

    </ui:composition>
</html>