src/main/java/cz/vut/fit/gja/controllers/PasteCodeController.java
package cz.vut.fit.gja.controllers;

import cz.vut.fit.gja.constants.FacesConstants;
import cz.vut.fit.gja.dao.LanguageDao;
import cz.vut.fit.gja.dto.ProjectDto;
import cz.vut.fit.gja.services.ProjectService;
import org.apache.log4j.Logger;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Controller;

import static cz.vut.fit.gja.constants.FacesConstants.PROJECT_DETAIL;
import static cz.vut.fit.gja.constants.FacesConstants.REDIRECT;
/**
 *
 */
@Lazy
@Controller
public class PasteCodeController extends ProjectController {

    private static Logger logger = Logger.getLogger(PasteCodeController.class.getName());

    @Autowired
    private ProjectDto projectDto;

    @Autowired
    private ProjectService projectService;

    @Autowired
    private LanguageDao languageDao;

    public String submit() {
        logger.debug("pasteCodeController#submit()");
        linkWithTags(projectDto);
        create(projectDto);
        savePasteCode(projectDto);
        invalidate();
        return String.format("%s?%s&%s=%s", PROJECT_DETAIL, REDIRECT, FacesConstants.PARAM_PROJECT_ID, Integer.toString(projectDto.getId()));
    }

    private void savePasteCode(ProjectDto projectDto) {
        projectService.saveCode(projectDto);
    }

    public ProjectDto getProjectDto() {
        return projectDto;
    }

    public void setProjectDto(ProjectDto projectDto) {
        this.projectDto = projectDto;
    }

    public LanguageDao getLanguageDao() {
        return languageDao;
    }

    public void setLanguageDao(LanguageDao languageDao) {
        this.languageDao = languageDao;
    }

}

src/main/java/cz/vut/fit/gja/controllers/ProjectController.java
package cz.vut.fit.gja.controllers;

import cz.vut.fit.gja.Scopes;
import cz.vut.fit.gja.constants.FacesConstants;
import cz.vut.fit.gja.controllers.data.LazyProjectModel;
import cz.vut.fit.gja.controllers.data.ProjectDataFilter;
import cz.vut.fit.gja.controllers.util.TagsAutocompleteBean;
import cz.vut.fit.gja.dto.ProjectDto;
import cz.vut.fit.gja.entities.Language;
import cz.vut.fit.gja.entities.Project;
import cz.vut.fit.gja.services.LanguageService;
import cz.vut.fit.gja.services.ProjectService;
import org.apache.log4j.Logger;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.RateEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static cz.vut.fit.gja.constants.FacesConstants.PROJECT_DETAIL;
import static cz.vut.fit.gja.constants.FacesConstants.REDIRECT;
import cz.vut.fit.gja.utils.FileSystemUtils;
import cz.vut.fit.gja.utils.SourceCodeFile;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.file.Files;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

@Lazy
@Scope(Scopes.VIEW)
@Controller
public class ProjectController extends BaseController implements Serializable {

    private static final Logger logger = Logger.getLogger(ProjectController.class);

    @Autowired
    private ProjectService projectService;

    @Autowired
    private LanguageService languageService;

    @Autowired
    private TagsAutocompleteBean autocompleteBean;

    private ProjectDto projectDto;

    private SourceCodeFile selectedSCFile;

    public ProjectController() {
    }

    public void create(ProjectDto projectDto) {
        projectService.create(projectDto);
    }

    public ProjectDto find(String idStr) {
        try {
            int id = Integer.valueOf(idStr);
            ProjectDto projectDto = find(id);
            this.projectDto = projectDto;
            return projectDto;
        } catch (NumberFormatException e) {
            return null;
        }

    }

    public ProjectDto find(int id) {
        if (id == 0) {
            return null;
        }
        ProjectDto projectDto = projectService.find(id);
        return projectDto;
    }

    public void loadProjectBean(int id) {

        ProjectDto dto = find(id);
        if (dto != null) {
            projectDto = dto;
        }
    }

    public void load(ComponentSystemEvent event) {
        String projectId = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap().get(FacesConstants.PARAM_PROJECT_ID);
        int id;
        try {
            id = Integer.valueOf(projectId);
        } catch (NumberFormatException e) {
            id = 0;
        }

        loadProjectBean(id);
    }

    public List<ProjectDto> findAll() {
        return projectService.findAll();
    }

    public List<ProjectDto> findAllByFilter() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        if (filter != null && filter.getLanguageName() != null) {
            return projectService.findByLanguage(filter.getLanguageName());
        }

        if (filter != null && filter.getTagName() != null) {
            return projectService.findByTag(filter.getTagName());
        }

        return Collections.emptyList();
    }

    public boolean isFiltered() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        return filter != null && (filter.getLanguageName() != null || filter.getTagName() != null);
    }

    public LazyProjectModel getLazyModel() {
        return new LazyProjectModel(projectService.findAll());
    }

    public String onFlowProcess(FlowEvent event) {
        return event.getNewStep();
    }

    protected void linkWithTags(ProjectDto projectDto) {
        projectService.linkWithTags(projectDto);
    }

    public boolean isOneFile() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length == 1);
    }

    public boolean isMoreFiles() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length > 1);
    }

    public String getFilesSourceCode(File name) {
        String code = "";
        try {
            CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
            decoder.onMalformedInput(CodingErrorAction.IGNORE);
            InputStreamReader sreader = new InputStreamReader(new FileInputStream(name), decoder);
            BufferedReader reader = new BufferedReader(sreader);
            String line;
            while ((line = reader.readLine()) != null) {
                code += line + "\n";
            }
        } catch (IOException ex) {
            return "An error while opening file occured! We are sorry.";
        }

        return code;
    }

    public String getSourceCodeFromFile(File file) {
        if (file.isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(file), decoder);
                BufferedReader reader = new BufferedReader(sreader);
                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                return "An error while opening file occured! We are sorry.";
            }

            return code;
        }
        return "An error occured, file " + file.getName() + " is not file!";
    }

    public String getSourceCode() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();

        if (list[0].isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(list[0]), decoder);
                BufferedReader reader = new BufferedReader(sreader);

                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                return "An error while opening file occured! We are sorry. " + ex.getMessage();
            }

            return code;
        }
        return "An error occured, file " + list[0].getName() + " is not file!";
    }

    public TreeNode getRoot() {
        TreeNode root = new DefaultTreeNode("root", null);
        root.setExpanded(true);
        root.setSelectable(false);

        if (projectDto != null) {
            File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
            getFolderContent(projectDataStore, root);
        }
        return root;
    }

    private void getFolderContent(File folder, TreeNode parentNode) {
        File[] list = folder.listFiles();

        for (File file : list) {
            if (file.isFile()) {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), FilenameUtils.getExtension(file.getName()), file.length(), file), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
            } else {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), "Folder", 0), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
                getFolderContent(file, node);
            }
        }
    }

    public SourceCodeFile getSelectedSCFile() {
        logger.debug("getSelectedSCFile");
        return selectedSCFile;
    }

    public void setSelectedSCFile(SourceCodeFile selectedSCFile) {
        logger.debug("setSelectedSCFile");
        this.selectedSCFile = selectedSCFile;
    }

    public List<String> getLanguages() {
        return languageNames(languageService.findAll());
    }

    public List<SelectItem> getLanguagesSelectItems() {
        return getLanguageItems(languageService.findAll());
    }

    private List<SelectItem> getLanguageItems(List<Language> all) {
        ArrayList<SelectItem> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(new SelectItem(language.getId(), language.getName()));
        }
        return langs;
    }

    private List<String> languageNames(List<Language> all) {
        ArrayList<String> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(language.getName());
        }

src/main/webapp/pages/index/filesUploadWizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <h:form enctype="multipart/form-data">
        <p:wizard flowListener="#{projectController.onFlowProcess}">

            <p:tab id="upload-files-info" title="Project informations">
                <ui:include src="uploadFileStep1.xhtml"/>
            </p:tab>

            <p:tab id="upload-files" title="Files upload">
                <ui:include src="uploadFilesStep2.xhtml"/>
            </p:tab>

        </p:wizard>
    </h:form>
</ui:composition>

src/main/webapp/pages/index/links.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml"
      xmlns:h="http://java.sun.com/jsf/html">
<h:head>
    <title>Facelet Title</title>
    <h:outputStylesheet name="css/jsfcrud.css"/>
</h:head>
<h:body>
    Hello from Facelets
    <br />
    <h:link outcome="welcomePrimefaces" value="Primefaces welcome page" />
    <br />
    <h:link outcome="/pages/language/List" value="Show All Language Items"/>
    <br />
    <h:link outcome="/pages/project/List" value="Show All Project Items"/>
    <br />
    <h:link outcome="/pages/tag/List" value="Show All Tag Items"/>
</h:body>



</html>

src/main/webapp/pages/index/pasteCode.xhtml
<?xml version="1.0" encoding="UTF-8"?>
<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
             xmlns:h="http://java.sun.com/jsf/html"
             xmlns:f="http://java.sun.com/jsf/core"
             xmlns:ui="http://java.sun.com/jsf/facelets"
             xmlns:p="http://primefaces.org/ui">
    <h:form id="paste-code-form">

        <p:messages showDetail="true" autoUpdate="true" closable="true" />

        <h:panelGrid columns="1" columnClasses="first,second">

            <p:outputLabel for="code" value="Code:"/>
            <p:inputTextarea id="code" value="#{projectDto.code}" required="true"
                             autoResize="true"
                             cols="80"/>
            <p:message for="code" display="code"/>

            <p:outputLabel for="language" value="Language:"/>
            <p:selectOneMenu id="language" value="#{projectDto.language}" required="true">
                <f:selectItem itemLabel="Select language" itemValue="" />
                <f:selectItems value="#{projectController.languagesSelectItems}" />
            </p:selectOneMenu>
            <p:message for="language" display="language"/>

            <p:outputLabel for="title" value="Title/Name:"/>
            <p:inputText id="title" value="#{projectDto.title}" required="true"/>
            <p:message for="title" display="title"/>

            <p:outputLabel for="expiration" value="Expiration:"/>
            <p:calendar id="expiration" value="#{projectDto.expiration}"/>
            <p:message for="expiration" display="expiration"/>

            <p:outputLabel for="tags" value="Tags:"/>
            <!--@elvariable id="t" type="cz.vut.fit.gja.dto.TagDto"-->
            <p:autoComplete id="tags"
                            value="#{projectDto.selectedTags}"
                            completeMethod="#{projectController.autocompleteBean.suggestion}"
                            multiple="true"
                            maxResults="10"
                            converter="#{tagConverter}"
                            var="t" itemLabel="#{t.name}" itemValue="#{t}"/>
            <p:message for="tags" display="tags"/>

            <p:outputLabel for="description" value="Description:"/>
            <p:editor id="description" value="#{projectDto.description}"
                      maxlength="#{FacesConstants.DESCRIPTION_LENGTH}"
                      width="497"/>
            <p:message for="expiration" display="description"/>

            <p:commandButton value="Submit" type="submit" action="#{pasteCodeController.submit}" />

        </h:panelGrid>
    </h:form>
</ui:composition>

src/main/webapp/pages/index/uploadFileStep1.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">

    <p:messages showDetail="true" autoUpdate="true" closable="true" />

    <h:panelGrid columns="3" columnClasses="first,second,third">

        <p:outputLabel for="language" value="Language:"/>
        <p:selectOneMenu id="language" value="#{projectDto.language}" required="true">
            <f:selectItem itemLabel="Select language" itemValue="" />
            <f:selectItems value="#{projectController.languagesSelectItems}" />
        </p:selectOneMenu>
        <p:message for="language" display="language"/>

        <p:outputLabel for="title" value="Title/Name:"/>
        <p:inputText id="title" value="#{projectDto.title}" required="true"/>
        <p:message for="title" display="title"/>

        <p:outputLabel for="expiration" value="Expiration:"/>
        <p:calendar id="expiration" value="#{projectDto.expiration}" rendered="true"/>
        <p:message for="expiration" display="expiration"/>

        <!--@elvariable id="t" type="cz.vut.fit.gja.dto.TagDto"-->
        <p:outputLabel for="tags" value="Tags:"/>
        <p:autoComplete id="tags"
                        value="#{projectDto.selectedTags}"
                        completeMethod="#{projectController.autocompleteBean.suggestion}"
                        multiple="true"
                        maxResults="10"
                        converter="#{tagConverter}"
                        var="t" itemLabel="#{t.name}" itemValue="#{t}"/>
        <p:message for="tags" display="tags"/>

        <p:outputLabel for="description" value="Description:"/>
        <p:editor id="description" value="#{projectDto.description}"
                         maxlength="#{FacesConstants.DESCRIPTION_LENGTH}"
                         width="497"/>
        <p:message for="expiration" display="description"/>

        <p:remoteCommand name="loadProperties">
            <f:setPropertyActionListener for="language" value="#{projectDto.language}" target="#{projectDto.language}"/>
            <f:setPropertyActionListener for="title" value="#{projectDto.title}" target="#{projectDto.title}"/>
            <f:setPropertyActionListener for="expiration" value="#{projectDto.expiration}" target="#{projectDto.expiration}"/>
        </p:remoteCommand>

        <!--<p:commandButton value="Upload" type="submit" action="# {uploadCodeController.submit}" />-->

    </h:panelGrid>
</ui:composition>

src/main/webapp/pages/index/uploadFilesStep2.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">

    <p:messages showDetail="true" autoUpdate="true" closable="true" />

    <h:panelGrid columns="1" styleClass="file-upload-grid">

        <p:outputLabel for="files" value="Files:"/>
        <p:fileUpload id="files" fileUploadListener="#{uploadCodeController.uploadFile}"
                      mode="advanced"
                      dragDropSupport="true"
                      multiple="true"
                      sizeLimit="100000"
                      update="growl"
                      required="true"
                      process="@this">
            <!--<h:outputText value="# {myBean.myFileName}"/>-->
        </p:fileUpload>
        <p:message for="files" display="files"/>
        <p:growl id="growl" showDetail="true"/>

        <!--<p:commandButton id="redirect" value="Go to project page" type="submit" action="# {uploadCodeController.redirectToProject}"/>-->

    </h:panelGrid>

</ui:composition>

src/main/webapp/pages/index/uploadZipStep2.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">

    <p:messages showDetail="true" autoUpdate="true" closable="true"/>

    <h:panelGrid columns="1" styleClass="file-upload-grid">

        <p:outputLabel for="files" value="Zip file:"/>
        <p:fileUpload id="files" fileUploadListener="#{uploadCodeController.uploadZipFile}"
                      mode="advanced"
                      dragDropSupport="true"
                      allowTypes="/(\.|\/)(zip|ZIP)$/"
                      sizeLimit="10000000"
                      update="growl"
                      required="true"
                      multiple="false"
                      process="@this">
            <!--<h:outputText value="# {myBean.myFileName}"/>-->
        </p:fileUpload>
        <p:message for="files" display="files"/>
        <p:growl id="growl" showDetail="true"/>

    </h:panelGrid>

</ui:composition>

src/main/webapp/pages/index/zipfileUploadWizard.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <h:form enctype="multipart/form-data">
        <p:wizard flowListener="#{projectController.onFlowProcess}">

            <p:tab id="upload-zip-info" title="Project informations">
                <ui:include src="uploadFileStep1.xhtml"/>
            </p:tab>

            <p:tab id="upload-zip" title="Zip file upload">
                <ui:include src="uploadZipStep2.xhtml"/>
            </p:tab>

        </p:wizard>
    </h:form>
</ui:composition>