src/main/java/cz/vut/fit/gja/dto/SearchDto.java
package cz.vut.fit.gja.dto;

import cz.vut.fit.gja.Scopes;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Component;

import java.io.Serializable;

/**
 *
 */
@Scope(Scopes.SESSION)
@Component
public class SearchDto implements Serializable {

    public static final String BEAN_NAME = "searchDto";

    private String query;

    public void setQuery(String query) {
        this.query = query;
    }

    public String getQuery() {
        return query;
    }
}

src/main/java/cz/vut/fit/gja/controllers/BaseController.java
package cz.vut.fit.gja.controllers;

import org.springframework.context.annotation.Lazy;

import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.Map;

/**
 *
 */
@Lazy
public class BaseController {

    protected Map<String, Object> getRequestMap() {
        return FacesContext.getCurrentInstance().getExternalContext().getRequestMap();
    }

    protected Map<String, Object> getSessionMap() {
        return FacesContext.getCurrentInstance().getExternalContext().getSessionMap();
    }

    protected Map<String, Object> getViewMap() {
        return FacesContext.getCurrentInstance().getViewRoot().getViewMap();
    }

    protected void invalidate() {
        FacesContext.getCurrentInstance().getExternalContext().invalidateSession();
    }

    protected void addMessage(FacesMessage.Severity severity, String title, String message) {
        FacesMessage m = new FacesMessage(severity, title, message);
        FacesContext.getCurrentInstance().addMessage(null, m);
    }

    protected Object get(String key) {
        return getSessionMap().get(key);
    }

    protected void put(String key, Object value) {
        getSessionMap().put(key, value);
    }
}

src/main/java/cz/vut/fit/gja/controllers/DashboardController.java
package cz.vut.fit.gja.controllers;

import cz.vut.fit.gja.constants.DashboardConstants;
import cz.vut.fit.gja.constants.FacesConstants;
import cz.vut.fit.gja.controllers.data.ProjectDataFilter;
import cz.vut.fit.gja.dto.ProjectDto;
import cz.vut.fit.gja.entities.Language;
import cz.vut.fit.gja.entities.Tag;
import cz.vut.fit.gja.services.LanguageService;
import cz.vut.fit.gja.services.ProjectService;
import cz.vut.fit.gja.services.TagService;
import org.primefaces.event.SelectEvent;
import org.primefaces.model.DashboardModel;
import org.primefaces.model.DefaultDashboardColumn;
import org.primefaces.model.DefaultDashboardModel;
import org.primefaces.model.tagcloud.DefaultTagCloudItem;
import org.primefaces.model.tagcloud.DefaultTagCloudModel;
import org.primefaces.model.tagcloud.TagCloudItem;
import org.primefaces.model.tagcloud.TagCloudModel;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.stereotype.Controller;

import javax.annotation.PostConstruct;
import javax.faces.application.FacesMessage;
import javax.faces.context.FacesContext;
import java.util.List;

/**
 *
 */
@Lazy
@Controller
public class DashboardController extends BaseController {

    private DashboardModel dashboardModel;
    private TagCloudModel tagCloudModel;
    private TagCloudModel languageCloudModel;

    @Autowired
    private ProjectService projectService;

    @Autowired
    private LanguageService languageService;
    
    @Autowired
    private TagService tagService;

    @PostConstruct
    void init() {
        dashboardModel = new DefaultDashboardModel() {{
            addColumn(new DefaultDashboardColumn() {{
                addWidget(DashboardConstants.TAG_CLOUD);
                addWidget(DashboardConstants.LANGUAGE_CLOUD);
            }});
            addColumn(new DefaultDashboardColumn() {{
                addWidget(DashboardConstants.TOP_RATED);
                addWidget(DashboardConstants.TOP_DOWNLOADED);
            }});
        }};
    }

    private void initTagCloudModel() {
        tagCloudModel = new DefaultTagCloudModel();

        Double max = tagService.aggregateMaxRelevance().doubleValue();
        for (Tag tag : tagService.findAll()) {
            DefaultTagCloudItem item = createTagCloudItem(tag.getName(), (long) tag.getRelevance(), max);
            
            tagCloudModel.addTag(item);
        }
    }

    private void initLanguageCloudModel() {
        languageCloudModel = new DefaultTagCloudModel();

        Double max = null;
        for (Object[] dto : projectService.aggregateLanguageCount()) {
            Language language = (Language) dto[0];
            Long count = (Long) dto[1];

            if (count == 0) {
                continue;
            }

            if (max == null) {
                max = count.doubleValue();
            }

            DefaultTagCloudItem item = createTagCloudItem(language.getName(), count, max);

            languageCloudModel.addTag(item);
        }

    }

    private DefaultTagCloudItem createTagCloudItem(String label, Long count, Double max) {
        // remaping to values 1-5 for tag cloud component
        int strength = (int) ((count.intValue() / max) * 5);
        if (strength == 0) {
            strength++;
        }
        return new DefaultTagCloudItem(label, strength);
    }

    public String detail(String id) {
        ProjectController.redirectToProjectUrl(id);
        return ProjectController.redirectToProjectUrl(id);
    }

    public void onLanguageSelect(SelectEvent event) {
        TagCloudItem item = (TagCloudItem) event.getObject();

        ProjectDataFilter projectDataFilter = new ProjectDataFilter();
        projectDataFilter.setLanguageName(item.getLabel());
        getSessionMap().put(FacesConstants.FILTER, projectDataFilter);

        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Language selected", item.getLabel());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }
    
    public void onTagSelect(SelectEvent event) {
        TagCloudItem item = (TagCloudItem) event.getObject();

        ProjectDataFilter projectDataFilter = new ProjectDataFilter();
        projectDataFilter.setTagName(item.getLabel());
        getSessionMap().put(FacesConstants.FILTER, projectDataFilter);

        FacesMessage msg = new FacesMessage(FacesMessage.SEVERITY_INFO, "Tag selected", item.getLabel());
        FacesContext.getCurrentInstance().addMessage(null, msg);
    }

    public DashboardModel getDashboardModel() {
        return dashboardModel;
    }

    public void setDashboardModel(DashboardModel dashboardModel) {
        this.dashboardModel = dashboardModel;
    }

    public TagCloudModel getTagCloudModel() {
        if (tagCloudModel == null)
            initTagCloudModel();
        return tagCloudModel;
    }

    public void setTagCloudModel(TagCloudModel tagCloudModel) {
        this.tagCloudModel = tagCloudModel;
    }

    public TagCloudModel getLanguageCloudModel() {
        if (languageCloudModel == null)
            initLanguageCloudModel();
        return languageCloudModel;
    }

    public void setLanguageCloudModel(TagCloudModel languageCloudModel) {
        this.languageCloudModel = languageCloudModel;
    }

    public List<ProjectDto> getMostDownloaded() {
        return projectService.getMostDownloaded();
    }

    public List<ProjectDto> getMostRated() {
        return projectService.getMostRated();
    }

    public void setProjectService(ProjectService projectService) {
        this.projectService = projectService;
    }

    public void setLanguageService(LanguageService languageService) {
        this.languageService = languageService;
    }

}

src/main/java/cz/vut/fit/gja/controllers/ProjectController.java
package cz.vut.fit.gja.controllers;

import cz.vut.fit.gja.Scopes;
import cz.vut.fit.gja.constants.FacesConstants;
import cz.vut.fit.gja.controllers.data.LazyProjectModel;
import cz.vut.fit.gja.controllers.data.ProjectDataFilter;
import cz.vut.fit.gja.controllers.util.TagsAutocompleteBean;
import cz.vut.fit.gja.dto.ProjectDto;
import cz.vut.fit.gja.entities.Language;
import cz.vut.fit.gja.entities.Project;
import cz.vut.fit.gja.services.LanguageService;
import cz.vut.fit.gja.services.ProjectService;
import org.apache.log4j.Logger;
import org.primefaces.event.FlowEvent;
import org.primefaces.event.RateEvent;
import org.primefaces.model.DefaultStreamedContent;
import org.primefaces.model.StreamedContent;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.context.annotation.Lazy;
import org.springframework.context.annotation.Scope;
import org.springframework.stereotype.Controller;

import javax.faces.application.FacesMessage;
import javax.faces.component.UIComponent;
import javax.faces.context.ExternalContext;
import javax.faces.context.FacesContext;
import javax.faces.convert.Converter;
import javax.faces.convert.FacesConverter;
import javax.faces.event.ComponentSystemEvent;
import javax.faces.model.SelectItem;
import javax.servlet.http.HttpServletRequest;
import java.io.IOException;
import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import static cz.vut.fit.gja.constants.FacesConstants.PROJECT_DETAIL;
import static cz.vut.fit.gja.constants.FacesConstants.REDIRECT;
import cz.vut.fit.gja.utils.FileSystemUtils;
import cz.vut.fit.gja.utils.SourceCodeFile;
import java.io.BufferedReader;
import java.io.File;
import java.io.FileInputStream;
import java.io.InputStreamReader;
import java.nio.charset.Charset;
import java.nio.charset.CharsetDecoder;
import java.nio.charset.CodingErrorAction;
import java.nio.file.Files;
import org.apache.commons.io.FilenameUtils;
import org.primefaces.model.DefaultTreeNode;
import org.primefaces.model.TreeNode;

@Lazy
@Scope(Scopes.VIEW)
@Controller
public class ProjectController extends BaseController implements Serializable {

    private static final Logger logger = Logger.getLogger(ProjectController.class);

    @Autowired
    private ProjectService projectService;

    @Autowired
    private LanguageService languageService;

    @Autowired
    private TagsAutocompleteBean autocompleteBean;

    private ProjectDto projectDto;

    private SourceCodeFile selectedSCFile;

    public ProjectController() {
    }

    public void create(ProjectDto projectDto) {
        projectService.create(projectDto);
    }

    public ProjectDto find(String idStr) {
        try {
            int id = Integer.valueOf(idStr);
            ProjectDto projectDto = find(id);
            this.projectDto = projectDto;
            return projectDto;
        } catch (NumberFormatException e) {
            return null;
        }

    }

    public ProjectDto find(int id) {
        if (id == 0) {
            return null;
        }
        ProjectDto projectDto = projectService.find(id);
        return projectDto;
    }

    public void loadProjectBean(int id) {

        ProjectDto dto = find(id);
        if (dto != null) {
            projectDto = dto;
        }
    }

    public void load(ComponentSystemEvent event) {
        String projectId = FacesContext.getCurrentInstance().
                getExternalContext().getRequestParameterMap().get(FacesConstants.PARAM_PROJECT_ID);
        int id;
        try {
            id = Integer.valueOf(projectId);
        } catch (NumberFormatException e) {
            id = 0;
        }

        loadProjectBean(id);
    }

    public List<ProjectDto> findAll() {
        return projectService.findAll();
    }

    public List<ProjectDto> findAllByFilter() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        if (filter != null && filter.getLanguageName() != null) {
            return projectService.findByLanguage(filter.getLanguageName());
        }

        if (filter != null && filter.getTagName() != null) {
            return projectService.findByTag(filter.getTagName());
        }

        return Collections.emptyList();
    }

    public boolean isFiltered() {
        ProjectDataFilter filter = (ProjectDataFilter) getSessionMap().get(FacesConstants.FILTER);

        return filter != null && (filter.getLanguageName() != null || filter.getTagName() != null);
    }

    public LazyProjectModel getLazyModel() {
        return new LazyProjectModel(projectService.findAll());
    }

    public String onFlowProcess(FlowEvent event) {
        return event.getNewStep();
    }

    protected void linkWithTags(ProjectDto projectDto) {
        projectService.linkWithTags(projectDto);
    }

    public boolean isOneFile() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length == 1);
    }

    public boolean isMoreFiles() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();
        return (list != null && list.length > 1);
    }

    public String getFilesSourceCode(File name) {
        String code = "";
        try {
            CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
            decoder.onMalformedInput(CodingErrorAction.IGNORE);
            InputStreamReader sreader = new InputStreamReader(new FileInputStream(name), decoder);
            BufferedReader reader = new BufferedReader(sreader);
            String line;
            while ((line = reader.readLine()) != null) {
                code += line + "\n";
            }
        } catch (IOException ex) {
            return "An error while opening file occured! We are sorry.";
        }

        return code;
    }

    public String getSourceCodeFromFile(File file) {
        if (file.isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(file), decoder);
                BufferedReader reader = new BufferedReader(sreader);
                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                return "An error while opening file occured! We are sorry.";
            }

            return code;
        }
        return "An error occured, file " + file.getName() + " is not file!";
    }

    public String getSourceCode() {
        File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
        File[] list = projectDataStore.listFiles();

        if (list[0].isFile()) {
            String code = "";
            try {
                CharsetDecoder decoder = Charset.forName("UTF-8").newDecoder();
                decoder.onMalformedInput(CodingErrorAction.IGNORE);
                InputStreamReader sreader = new InputStreamReader(new FileInputStream(list[0]), decoder);
                BufferedReader reader = new BufferedReader(sreader);

                String line;
                while ((line = reader.readLine()) != null) {
                    code += line + "\n";
                }
            } catch (IOException ex) {
                ex.printStackTrace();
                return "An error while opening file occured! We are sorry. " + ex.getMessage();
            }

            return code;
        }
        return "An error occured, file " + list[0].getName() + " is not file!";
    }

    public TreeNode getRoot() {
        TreeNode root = new DefaultTreeNode("root", null);
        root.setExpanded(true);
        root.setSelectable(false);

        if (projectDto != null) {
            File projectDataStore = FileSystemUtils.getProjectDataStore(projectDto.getId());
            getFolderContent(projectDataStore, root);
        }
        return root;
    }

    private void getFolderContent(File folder, TreeNode parentNode) {
        File[] list = folder.listFiles();

        for (File file : list) {
            if (file.isFile()) {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), FilenameUtils.getExtension(file.getName()), file.length(), file), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
            } else {
                TreeNode node = new DefaultTreeNode(new SourceCodeFile(file.getName(), "Folder", 0), parentNode);
                node.setExpanded(true);
                node.setSelectable(false);
                getFolderContent(file, node);
            }
        }
    }

    public SourceCodeFile getSelectedSCFile() {
        logger.debug("getSelectedSCFile");
        return selectedSCFile;
    }

    public void setSelectedSCFile(SourceCodeFile selectedSCFile) {
        logger.debug("setSelectedSCFile");
        this.selectedSCFile = selectedSCFile;
    }

    public List<String> getLanguages() {
        return languageNames(languageService.findAll());
    }

    public List<SelectItem> getLanguagesSelectItems() {
        return getLanguageItems(languageService.findAll());
    }

    private List<SelectItem> getLanguageItems(List<Language> all) {
        ArrayList<SelectItem> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(new SelectItem(language.getId(), language.getName()));
        }
        return langs;
    }

    private List<String> languageNames(List<Language> all) {
        ArrayList<String> langs = new ArrayList<>();
        for (Language language : all) {
            langs.add(language.getName());
        }

src/main/webapp/pages/overview/dashboard.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <h:form>
        <div id="board">
            <p:dashboard model="#{dashboardController.dashboardModel}" disabled="true">

                <p:panel id="#{DashboardConstants.TAG_CLOUD}" header="Tags">
                    <ui:include src="tagCloud.xhtml"/>
                </p:panel>

                <p:panel id="#{DashboardConstants.LANGUAGE_CLOUD}" header="Languages">
                    <ui:include src="languageCloud.xhtml"/>
                </p:panel>

                <p:panel id="#{DashboardConstants.TOP_DOWNLOADED}" header="Most downloaded">
                    <ui:include src="mostDownloaded.xhtml"/>
                </p:panel>

                <p:panel id="#{DashboardConstants.TOP_RATED}" header="Top rated">
                    <ui:include src="mostRated.xhtml"/>
                </p:panel>

            </p:dashboard>
        </div>
    </h:form>

    <ui:include src="dataGrid.xhtml"/>

</ui:composition>

src/main/webapp/pages/overview/dataGrid.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <h:form prependId="false" id="board-grid">
        <!--@elvariable id="p" type="cz.vut.fit.gja.dto.ProjectDto"-->
        <p:dataTable id="dataTable" var="p"
                     rendered="#{projectController.filtered}"
                     value="#{projectController.findAllByFilter()}"
                     paginator="true" rows="10"
                     paginatorTemplate="{CurrentPageReport}  {FirstPageLink} {PreviousPageLink} {PageLinks} {NextPageLink} {LastPageLink} {RowsPerPageDropdown}"
                     rowsPerPageTemplate="5,10,15">
            <f:facet name="header">
                Projects
            </f:facet>

            <p:column width="10%">
                <f:facet name="header">
                    <h:outputText value="View Detail" />
                </f:facet>
            <p:commandButton icon="ui-icon-search" title="View Detail" action="#{projectController.redirectToProjectUrl(p.id)}"/>
            </p:column>

            <p:column>
                <f:facet name="header">
                    <h:outputText value="Title" />
                </f:facet>
                <h:outputText value="#{p.title}" />
            </p:column>

            <p:column>
                <f:facet name="header">
                    <h:outputText value="Language" />
                </f:facet>
                <h:outputText value="#{p.languageDto.name}" />
            </p:column>

        </p:dataTable>
    </h:form>

</ui:composition>

src/main/webapp/pages/overview/languageCloud.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <p:tagCloud model="#{dashboardController.languageCloudModel}">
        <p:ajax event="select" update=":#{p:component('board-grid')} msg" listener="#{dashboardController.onLanguageSelect}" />
    </p:tagCloud>
    <p:growl id="msg" showDetail="true" />
</ui:composition>

src/main/webapp/pages/overview/main.xhtml
<?xml version='1.0' encoding='UTF-8' ?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html  xmlns="http://www.w3.org/1999/xhtml"
       xmlns:h="http://java.sun.com/jsf/html"
       xmlns:f="http://java.sun.com/jsf/core"
       xmlns:ui="http://java.sun.com/jsf/facelets"
       xmlns:p="http://primefaces.org/ui">
<ui:composition template="/resources/template/main.xhtml">

    <ui:param name="pageTitle" value="Code Portal" />

    <ui:define name="header">
        Code Portal
    </ui:define>

    <ui:define name="main">
        <ui:include src="dashboard.xhtml"/>
    </ui:define>

</ui:composition>
</html>

src/main/webapp/pages/overview/mostDownloaded.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">

    <!--@elvariable id="p" type="cz.vut.fit.gja.dto.ProjectDto"-->
    <p:dataList value="#{dashboardController.mostDownloaded}" var="p"
                paginator="true" rows="5"
                paginatorAlwaysVisible="false"
                paginatorTemplate="{PreviousPageLink} {CurrentPageReport} {NextPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,15" type="none">

        <div class="item">
            <p:commandButton icon="ui-icon-search" title="View Detail" action="#{dashboardController.detail(p.id)}"/>

            <h:outputText value="#{p.title} (#{p.languageDto != null ? p.languageDto.name : 'unknown language' })" style="margin-left:10px" />
        </div>
    </p:dataList>

</ui:composition>

src/main/webapp/pages/overview/mostRated.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">

    <!--@elvariable id="p" type="cz.vut.fit.gja.dto.ProjectDto"-->
    <p:dataList value="#{dashboardController.mostRated}" var="p"
                paginator="true" rows="5"
                paginatorAlwaysVisible="false"
                paginatorTemplate="{PreviousPageLink} {CurrentPageReport} {NextPageLink} {RowsPerPageDropdown}"
                rowsPerPageTemplate="5,10,15" type="none">

        <div class="item">
            <p:commandButton icon="ui-icon-search" title="View Detail" action="#{dashboardController.detail(p.id)}"/>

            <h:outputText value="#{p.title} (#{p.languageDto != null ? p.languageDto.name : 'unknown language' })" style="margin-left:10px" />
        </div>
    </p:dataList>
</ui:composition>

src/main/webapp/pages/overview/tagCloud.xhtml
<?xml version="1.0" encoding="UTF-8"?>

<ui:composition  xmlns="http://www.w3.org/1999/xhtml"
                 xmlns:h="http://java.sun.com/jsf/html"
                 xmlns:f="http://java.sun.com/jsf/core"
                 xmlns:ui="http://java.sun.com/jsf/facelets"
                 xmlns:p="http://primefaces.org/ui">
    <p:tagCloud model="#{dashboardController.tagCloudModel}">  
        <p:ajax event="select" update=":#{p:component('board-grid')} msg" listener="#{dashboardController.onTagSelect}" />  
    </p:tagCloud>  
</ui:composition>